### ISSUE TITLE
Chuango PIR device unknown

### ISSUE THREAD

**Issue by v0d0r** [enesbcs/pyrtl433#1]
I stumbled onto this plugin for 433 and seems like a much cleaner solution as it fetches the 433 data from MQTT.
Having said that I am having some difficulty getting a Chuango PIR device created in Domoticz.  I have confirmed that device creation is enabled in both the plugin and in domoticz. (My other Shelly relays auto create from a similar Domoticz plugin)
Any pointers you can provide. I do not exactly know what else to look for.

# I am running the rtl_433 binary as follows:
rtl_433 -c /usr/local/etc/rtl_433/rtl_433.conf -v -R 29 -F mqtt://localhost 1883 retain 0

# When I query the MQTT topic rtl_433 I can see the following entries:
rtl_433/raspberrypi/devices/Chuango-Security/24765/time 2020-09-08 08:31:16.578465
rtl_433/raspberrypi/devices/Chuango-Security/24765/protocol 29
rtl_433/raspberrypi/devices/Chuango-Security/24765/id 24765
rtl_433/raspberrypi/devices/Chuango-Security/24765/cmd 24H Zone
rtl_433/raspberrypi/devices/Chuango-Security/24765/cmd_id 11
rtl_433/raspberrypi/devices/Chuango-Security/24765/mod ASK
rtl_433/raspberrypi/devices/Chuango-Security/24765/freq 433.96301
rtl_433/raspberrypi/devices/Chuango-Security/24765/rssi -0.106258
rtl_433/raspberrypi/devices/Chuango-Security/24765/snr 16.86598
rtl_433/raspberrypi/devices/Chuango-Security/24765/noise -16.9722

rtl_433/raspberrypi/events {"time":"2020-09-08 08:31:16.578465","protocol":29,"model":"Chuango-Security","id":24765,"cmd":"24H Zone","cmd_id":11,"mod":"ASK","freq":433.96301,"rssi":-0.106258,"snr":16.86598,"noise":-16.9722}

# I can also see in the rtl_433 terminal window similar to the above
rtl_433/raspberrypi/states {"time":"2020-09-08 08:39:26.255403","enabled":137,"frames":{"count":37,"fsk":0,"events":19},"stats":[{"device":29,"name":"Chuango Security Technology","events":19,"ok":19,"messages":19},{"device":29,"name":"Chuango Security Technology","events":19,"ok":19,"messages":19}]}

**Comment by enesbcs** [comment]
> rtl_433/raspberrypi/devices/Chuango-Security/24765/cmd 24H Zone
> rtl_433/raspberrypi/devices/Chuango-Security/24765/cmd_id 11
> 
> rtl_433/raspberrypi/events {"time":"2020-09-08 08:31:16.578465","protocol":29,"model":"Chuango-Security","id":24765,"cmd":"24H Zone","cmd_id":11,"mod":"ASK","freq":433.96301,"rssi":-0.106258,"snr":16.86598,"noise":-16.9722}

This plugin uses the /events line to decode data. "cmd" and "cmd_id" is unknown to me, please specify its possible values and the suggested Domoticz device type.
