### ISSUE TITLE
Wind sensor datatype

### ISSUE THREAD

**Issue by HanSyt** [enesbcs/pyrtl433#2]
Hi,

Looks looks a nice project, I installed the pluging without problems.
I can see [RTL-SDR] messages in the log from my 2 desired weather sensors (the work directly in influxdb).
However the plugin does not place them in the devices tab (in the log I see it pings the mqtt server).

Maybe, Domoticz (2020.02) has problems with this version?
Or I am doing something wrong..

![image](https://user-images.githubusercontent.com/56794786/97112483-da8d9b00-16e4-11eb-8c7b-2b3aa1d7f1fe.png)

**Comment by enesbcs** [comment]
Either Domoticz changed in an interesting way, or rtlsdr sends an invalid JSON payload... as names has to be quoted by " and not ' as per the standard.

**Comment by HanSyt** [comment]
There is native rtl_433 support in Domoticz on the hardware page. Used it with -R 42 -R 147 parameter, that worked, but not to good, Domoticz was crashing after a couple of hours. After a restart it crashed again until I removed rtl_433 from the hardware tab.
Maybe Domoticz has changed a bit?

**Comment by enesbcs** [comment]
I think it is now fixed at commit https://github.com/enesbcs/pyrtl433/commit/e82f283a4b89d110d6b29097199a56e683d9dda0

**Comment by HanSyt** [comment]
The plugin is now accepting my Hideki-Wind device, my TFA-Drop is missing - I don't see any MQTT messages in the logs from 
![image](https://user-images.githubusercontent.com/56794786/97694772-5d2aa780-1aa3-11eb-8c6f-76120471cffe.png)
I guess I have to wait for some rain probably.

I start rtl_433 with supervisord:
![image](https://user-images.githubusercontent.com/56794786/97695157-e6da7500-1aa3-11eb-9048-a171ff8098e7.png)
In the picture you can see R 42 and R 147 as devices ( I don't need to register my neighbours devices), also a double F parameter to feed both MQTT and Influxdb (seems to be working very well)

So when de TFA-Drop appears after a shower I will inform you.

Another suggestion: in the README.MD file I think the initial git command should be "git **clone** https://etc..". Clone is missing

**Comment by HanSyt** [comment]
Good, there was rain, but still no TFA-Drop, I noticed something else too:
![image](https://user-images.githubusercontent.com/56794786/97703158-72f29980-1ab0-11eb-99c3-05aeb5c4f52a.png)

I added sensor 19..
I have a lot of 433 temperature devices, however it only finds 3. However.. temperatures on number 3 jump from 19.3 to 14.7, it seems that the device number isn't correctly interpreted. 
![image](https://user-images.githubusercontent.com/56794786/97703393-d4b30380-1ab0-11eb-8e78-1702dcbca523.png)

This is the output of rtl_433, where you can see how the temperature sensors and tfa-drop manifest themselves
![image](https://user-images.githubusercontent.com/56794786/97703807-8baf7f00-1ab1-11eb-99c8-19048c1bad54.png)

**Comment by enesbcs** [comment]
Please send only the MQTT parts sent from rtl_433 .. i can not use console outputs for anything.

**Comment by HanSyt** [comment]
[mqtt_433.txt](https://github.com/enesbcs/pyrtl433/files/5467699/mqtt_433.txt)
Hi ALexander,
Enclosed the output of mosquitto_sub -v -t "rtl_433/#"
I enabled all sensors for this trace to give you as much information as possible.

**Comment by enesbcs** [comment]
I see. "id" field is not used in naming as some sensor regenerates ids when changing battery... but i can add an option to the plugin to include id's in device names.

**Comment by HanSyt** [comment]
That would probably solve the problem with the temperature sensors. 
I guess you are using channel for naming it, that could explain the missing of TFA-Drop:

rtl_433/domoticz/events {"time":"2020-10-30 22:11:14","model":"Hideki-Wind","id":10,"channel":4,"battery_ok":1,"temperature_C":14.0,"wind_avg_km_h":4.18429,"wind_max_km_h":1.12654,"wind_approach":2,"wind_dir_deg":45.0,"mic":"CRC"}
rtl_433/domoticz/events {"time":"2020-10-30 22:12:04","model":"TFA-Drop","id":708744,"battery_ok":1,"rain_mm":24.638,"mic":"CHECKSUM"}

TFA-Drop does not send a channel, only an "id:", so maybe "id:" is better than "channel:"?

**Comment by enesbcs** [comment]
> TFA-Drop does not send a channel, only an "id:", so maybe "id:" is better than "channel:"?

Maybe it will better for you. But other users with randomly generated ID's will be worse.

**Comment by enesbcs** [comment]
"ID" field usage for distinction units can be selected from plugin settings from commit https://github.com/enesbcs/pyrtl433/commit/fd9b3dd8f2806444aca83457e4af965752f77ad3

**Comment by HanSyt** [comment]
This looks good, all devices are recognised now, all temperature sensors are showing up.
![image](https://user-images.githubusercontent.com/56794786/97800603-d9a1bf80-1c36-11eb-94bd-3547453b06d8.png)

However, I think the TFA-Drop has a value problem, the device reports its rain - normally this is all the rain since its first start. The value in Domoticz is increasing despite there is no rain, I guess some other value is counted as well. The mqtt line is shorter, maybe the plugin is counting  parameters (like in bash awk '{print $5}')?  
![image](https://user-images.githubusercontent.com/56794786/97800736-ff7b9400-1c37-11eb-9f19-6c107ef49d39.png)


With MQTT is looks like this:
![image](https://user-images.githubusercontent.com/56794786/97800566-87609e80-1c36-11eb-9c06-255c8296182a.png)
With Domoticz, rain values are not to good
![image](https://user-images.githubusercontent.com/56794786/97800574-9e06f580-1c36-11eb-84be-0317d3c37cf3.png)

In Grafana the values are correct (directly from rtl_433)
![image](https://user-images.githubusercontent.com/56794786/97800638-25546900-1c37-11eb-83c4-53f537f425d2.png)

**Comment by enesbcs** [comment]
> However, I think the TFA-Drop has a value problem, the device reports its rain - normally this is all the rain since its first start. The value in Domoticz is increasing despite there is no rain, I guess some other value is counted as well. The mqtt line is shorter, maybe the plugin is counting parameters (like in bash awk '{print $5}')?

Yes the plugin is counting as the Domoticz Python Development manual says that "Rain" device needs to parameters, first is RainLastHour_MM and second is an "everincreasing counter".
https://www.domoticz.com/wiki/Developing_a_Python_plugin#Available_Device_Types

**Comment by HanSyt** [comment]
Hi Alexander,

If you look at this picture of domoticz:
![image](https://user-images.githubusercontent.com/56794786/97809932-92d0bb80-1c70-11eb-87ca-e0aa429329b5.png)
and compare it to the one above, you will see that the amount of rain today is around 123 meters.
I guess that is not realtistic,

TFA-Drop sends only one value, that is the total amount of rain: 28.194 mm, that is the rate that the plugin places in mm/h value in the center of the picture,
![image](https://user-images.githubusercontent.com/56794786/97810039-4fc31800-1c71-11eb-8244-b2da98469d02.png)
That value should actually be on the top right, and de rain rate of the last hour should be calculated
 from the value 28.194.
So I guess something goes wrong here, I assume that the ever that the first and second argument are in the wrong order?
![image](https://user-images.githubusercontent.com/56794786/97810172-41293080-1c72-11eb-874e-b9cb2aa1be5d.png)

**Comment by enesbcs** [comment]
> That value should actually be on the top right, and de rain rate of the last hour should be calculated
> from the value 28.194.

And how?

**Comment by enesbcs** [comment]
Altered in commit https://github.com/enesbcs/pyrtl433/commit/fc1155c750def8f28cf303ada79b67d4d83952c8

Returned values can be modified in plugin.py at line 552 if anyone has time, ideas and motivation.

**Comment by HanSyt** [comment]
Hi ALexander,

First, I'm not a python programmer (was Delphi programmer), so maybe I am suggesting something that does not cope with python.
Also I can only speak for the TFA-Drop. TFA-Srop sends only one value, that is the total amount of rain
![image](https://user-images.githubusercontent.com/56794786/97812475-d41d9700-1c81-11eb-9ee8-86d5be8e0c48.png)
So in this case rain_mm is the total amount of rain, this formula needs to be changed I think:
![image](https://user-images.githubusercontent.com/56794786/97812740-b7825e80-1c83-11eb-880c-cb0478ec541e.png)

So, I would somehow change this in
![image](https://user-images.githubusercontent.com/56794786/97813363-f2869100-1c87-11eb-9840-e7cbcaad15e9.png)
rain is the value of the sensor NOW and prevdata[1] should be the value of the sensor NOW minus 1 hour.

Also
![image](https://user-images.githubusercontent.com/56794786/97812915-05e42d00-1c85-11eb-868b-aa49c116f76d.png)
Should be changed in:
![image](https://user-images.githubusercontent.com/56794786/97813232-0251a580-1c87-11eb-92f1-4ad2c17e8a75.png)

Result now is:
![image](https://user-images.githubusercontent.com/56794786/97813248-1d241a00-1c87-11eb-9d01-00624e9b9ef8.png)
However.. it should take an hour to get in sync.. The plugin.py is now a bit messy here, due to my changes, I did not check how prevdata was calculated, I guess you made an array and stored all last hours values in it?

**Comment by enesbcs** [comment]
> However.. it should take an hour to get in sync.. The plugin.py is now a bit messy here, due to my changes, I did not check how prevdata was calculated, I guess you made an array and stored all last hours values in it?

prevdata not calculated, read from Domoticz, I've erased this code from the plugin.
I have no plans to store any values in the plugin.

> rain is the value of the sensor NOW and prevdata[1] should be the value of the sensor NOW minus 1 hour.

Its way over my knowledge.

**Comment by HanSyt** [comment]
You wrote this plugin, so your knowledge is ok, I couldn't have done it.

If prevdata[1] represents the data of an hour ago in Domoticz, this could be working:
![image](https://user-images.githubusercontent.com/56794786/97814960-375ff700-1c8b-11eb-8934-c3255e668603.png)

I will check it tomorrow (depends if it rains when I'm awake).

**Comment by enesbcs** [comment]
> If prevdata[1] represents the data of an hour ago in Domoticz, this could be working:

There are no guarantee that prevdata contains data from an hour ago... it is simply the last data registered it can be 5 minutes or half an hour.
